# Project: ProjectEuler
# Makefile created by Dev-C++ 5.6.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../src/ProjectEuler.o
LINKOBJ  = ../src/ProjectEuler.o
LIBS     = -static-libgcc -g3
INCS     = 
CXXINCS  = 
BIN      = ../bin/ProjectEuler.exe
CXXFLAGS = $(CXXINCS) -g3 -std=c++11
CFLAGS   = $(INCS) -g3 -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../src/ProjectEuler.o: ../src/ProjectEuler.cpp
	$(CPP) -c ../src/ProjectEuler.cpp -o ../src/ProjectEuler.o $(CXXFLAGS)
